language: generic
dist: trusty

env:
  - IMAGE_TO_BUILD=prestodev/hdp2.5-hive-kerberized IMAGE_TO_TEST=hdp2.5-hive
  - IMAGE_TO_BUILD=prestodev/hdp2.6-hive-kerberized IMAGE_TO_TEST=hdp2.6-hive
  - IMAGE_TO_BUILD=prestodev/hdp3.1-hive-kerberized IMAGE_TO_TEST=hdp3.1-hive
  - IMAGE_TO_BUILD=prestodev/cdh5.12-hive-kerberized IMAGE_TO_TEST=cdh5.12-hive
  - IMAGE_TO_BUILD=prestodev/cdh5.15-hive-kerberized IMAGE_TO_TEST=cdh5.15-hive
  - IMAGE_TO_BUILD=prestodev/iop4.2-hive IMAGE_TO_TEST=iop4.2-hive

services: 
  - docker

install: make ${IMAGE_TO_BUILD}

script: make test IMAGE_TO_TEST=${IMAGE_TO_TEST}
